# -*- coding: utf-8 -*-
"""appMLPP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xt9vFVLJnrJlgpGwBCZxYeUwjzW3DqZ9
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectFromModel
import plotly.graph_objects as go
from datetime import datetime, timedelta
import joblib

# === Load historical data ===
def load_data(ticker, period='2y'):
    df = yf.download(ticker, period=period, interval='1d')
    df.dropna(inplace=True)
    return df

# === Add technical indicators ===
def add_indicators(df):
    for period in [5, 10, 21, 50, 100, 200]:
        df[f'SMA{period}'] = df['Close'].rolling(window=period).mean()
        df[f'EMA{period}'] = df['Close'].ewm(span=period, adjust=False).mean()

    df['RSI'] = 100 - (100 / (1 + df['Close'].diff().clip(lower=0).rolling(14).mean() /
                             (-df['Close'].diff().clip(upper=0).rolling(14).mean())))
    df['MA20'] = df['Close'].rolling(window=20).mean()
    df['STD20'] = df['Close'].rolling(window=20).std()
    df['UpperBB'] = df['MA20'] + 2 * df['STD20']
    df['LowerBB'] = df['MA20'] - 2 * df['STD20']
    ema12 = df['Close'].ewm(span=12, adjust=False).mean()
    ema26 = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = ema12 - ema26
    df['Signal_Line'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['TR'] = np.maximum(df['High'] - df['Low'], np.maximum(abs(df['High'] - df['Close'].shift(1)), abs(df['Low'] - df['Close'].shift(1))))
    df['ATR14'] = df['TR'].rolling(window=14).mean()
    low14 = df['Low'].rolling(window=14).min()
    high14 = df['High'].rolling(window=14).max()
    df['%K'] = 100 * (df['Close'] - low14) / ((high14 - low14) + 1e-10)
    df['%D'] = df['%K'].rolling(window=3).mean()
    df['OBV'] = (np.sign(df['Close'].diff()) * df['Volume']).fillna(0).cumsum()
    df['TP'] = (df['High'] + df['Low'] + df['Close']) / 3
    df['CCI'] = (df['TP'] - df['TP'].rolling(20).mean()) / (0.015 * df['TP'].rolling(20).std())
    df['ROC'] = df['Close'].pct_change(periods=12) * 100
    df['Williams_%R'] = -100 * ((high14 - df['Close']) / (high14 - low14 + 1e-10))
    return df

# === Add lag and statistical features ===
def add_features(df):
    for lag in range(1, 6):
        df[f'Close_lag_{lag}'] = df['Close'].shift(lag)
        df[f'Return_lag_{lag}'] = df['Close'].pct_change().shift(lag)
        df[f'Direction_lag_{lag}'] = (df['Close'].pct_change().shift(lag) > 0).astype(int)

    df['Daily_Return'] = df['Close'].pct_change()
    df['Volatility_5'] = df['Daily_Return'].rolling(window=5).std()
    df['Volatility_10'] = df['Daily_Return'].rolling(window=10).std()
    df['Price_Range'] = df['High'] - df['Low']
    df['Body_Size'] = abs(df['Close'] - df['Open'])
    df['Volume_Change'] = df['Volume'].pct_change()
    df['Day_of_Week'] = df.index.dayofweek
    df['MACD_RSI'] = df['MACD'] * df['RSI']
    df['ADX_Body'] = df['ATR14'] * df['Body_Size']
    df['Month'] = df.index.month
    df['Is_Month_Start'] = df.index.is_month_start.astype(int)
    df['Is_Quarter_End'] = df.index.is_quarter_end.astype(int)
    df['Target'] = df['Close'].pct_change().shift(-1)
    return df

# === Load model and scaler ===
def load_model_and_scaler():
    model = joblib.load('xgb_model.joblib')
    scaler = joblib.load('scaler.joblib')
    selector = joblib.load('selector.joblib')
    return model, scaler, selector

# === Predict price ===
def predict_price(df, model, scaler, selector):
    df = df.dropna()
    
    # Ambil baris terakhir sebagai input prediksi
    X_raw = df.drop(['Target', 'Close'], axis=1).iloc[-1:]
    
    # Pastikan kolom sama urutan dan jumlahnya seperti saat training
    X_scaled = scaler.transform(X_raw)
    X_selected = selector.transform(X_scaled)
    
    y_pred_return = model.predict(X_selected)[0]
    y_pred_price = df['Close'].iloc[-1] * (1 + y_pred_return)
    return y_pred_price, y_pred_return


# === Streamlit App ===
st.set_page_config(page_title="Prediksi Harga Aset", layout="wide")
st.title("📈 Prediksi Harga Penutupan Aset - Streamlit App")

with st.sidebar:
    ticker = st.text_input("Masukkan Ticker (contoh: AAPL, BTC-USD, etc)", value="AAPL")

if ticker:
    st.subheader(f"📊 Data dan Prediksi untuk {ticker}")
    with st.spinner("Mengunduh data dan memproses..."):
        df = load_data(ticker)
        df = add_indicators(df)
        df = add_features(df)
        model, scaler, selector = load_model_and_scaler()
        pred_price, pred_return = predict_price(df, model, scaler, selector)

    last_close = float(df['Close'].iloc[-1])
    pred_price = float(pred_price)
    delta = pred_price - last_close
    arah = "⬆️ Naik" if delta > 0 else "⬇️ Turun"

       # Plot harga + prediksi
    fig = go.Figure()

    if not df['Close'].isna().all() and not np.isnan(pred_price):
        fig.add_trace(go.Scatter(x=df.index, y=df['Close'], name='Close'))
        fig.add_trace(go.Scatter(
            x=[df.index[-1] + timedelta(days=1)],
            y=[pred_price],
            name='Prediksi',
            mode='markers+text',
            text=[f"${pred_price:.2f}"],
            textposition="top center",
            marker=dict(color='red', size=10)
        ))
    else:
        st.warning(\"⚠️ Data tidak valid untuk divisualisasikan.\")

    fig.update_layout(title=f\"{ticker} - Harga Penutupan & Prediksi Besok\", xaxis_title=\"Tanggal\", yaxis_title=\"Harga\")

    st.plotly_chart(fig, use_container_width=True)

